$(document).ready(function(){
    $("#" + (new Date().getDate())).toggleClass('date');
    $(".first").click(function(){
        $(this).toggleClass('opened');
        $("#place0").slideToggle(1000);
        $("#conditions0").slideToggle(1500);
        $("#conditionsDesc0").slideToggle(2000);
        $("#currentTemp0").slideToggle(2500);
        $("#image0").slideToggle(3000);
    });
    $(".second").click(function(){
        $(this).toggleClass('opened');
        $("#place1").slideToggle(1000);
        $("#conditions1").slideToggle(1500);
        $("#conditionsDesc1").slideToggle(2000);
        $("#currentTemp1").slideToggle(2500);
        $("#image1").slideToggle(3000);
    });
    $(".third").click(function(){
        $(this).toggleClass('opened');
        $("#place2").slideToggle(1000);
        $("#conditions2").slideToggle(1500);
        $("#conditionsDesc2").slideToggle(2000);
        $("#currentTemp2").slideToggle(2500);
        $("#image2").slideToggle(3000);
    });
    $(".fourth").click(function(){
        $(this).toggleClass('opened');
        $("#place3").slideToggle(1000);
        $("#conditions3").slideToggle(1500);
        $("#conditionsDesc3").slideToggle(2000);
        $("#currentTemp3").slideToggle(2500);
        $("#image3").slideToggle(3000);
    });
    $(".fifth").click(function(){
        $(this).toggleClass('opened');
        $("#place4").slideToggle(1000);
        $("#conditions4").slideToggle(1500);
        $("#conditionsDesc4").slideToggle(2000);
        $("#currentTemp4").slideToggle(2500);
        $("#image4").slideToggle(3000);
    });
});